### ISSUE TITLE
ExpandedExtension already define

### ISSUE THREAD

**Issue by mrvyas417** [jayeshpansheriya/awesome_extensions#15]
flexible_extansion.dat and expanded_extension.dart have same name "ExpandedExtension" which ,create conflicts so you have to change the name

**Comment by mrvyas417** [comment]
flexible_extansion.dat and expanded_extension.dart have same name "ExpandedExtension" which  ,create conflicts so you have to change the name

**Comment by jayeshpansheriya** [comment]
Definitely.

**Comment by mrvyas417** [comment]
Thanks
 for you quick response

**Comment by jeevassomasundaram** [comment]
> flexible_extansion.dat and expanded_extension.dart have same name "ExpandedExtension" which ,create conflicts so you have to change the name

Yes face same issue

**Comment by jayeshpansheriya** [comment]
@mrvyas417  Please Use latest version,
Commit: https://github.com/jayeshpansheriya/awesome_extensions/commit/8aa6fef2c857592511debe01606381bb6cd14aba

**Comment by jayeshpansheriya** [comment]
> > flexible_extansion.dat and expanded_extension.dart have same name "ExpandedExtension" which ,create conflicts so you have to change the name
> 
> Yes face same issue

please use latest version

**Comment by jayeshpansheriya** [comment]
its resolved in new version, Please reopen if you face any issue regarding flexible or expanded extension

**Comment by mrvyas417** [comment]
> its resolved in new version, Please reopen if you face any issue regarding flexible or expanded extension

yes sure
