### ISSUE TITLE
Use generics properly in extensions

### ISSUE THREAD

**Issue by TekExplorer** [jayeshpansheriya/awesome_extensions#20]
For instance
 `void pop<T>({result}) => Navigator.pop(this, result);`
should be
`void pop<T extends Object?>([T? result]) => Navigator.pop<T>(this, result);`

Also, why `result` is named here makes no sense to me at all.
There's so many more like this

whenever i use `context.pop()` my linter always complains about failing to infer type arguments because of this.

**Comment by jayeshpansheriya** [comment]
@TekExplorer Create PR, i will review it.

**Comment by jayeshpansheriya** [comment]
@TekExplorer  please use this version: https://pub.dev/packages/awesome_extensions/versions/2.0.18-pre
