### ISSUE TITLE
flutter build web --wasm failing

### ISSUE THREAD

**Issue by satvikreddy** [jayeshpansheriya/awesome_extensions#33]
With release of flutter 3.22, we can now build flutter web with wasm

Unfortunately, this package prevents that right now.

Migration guide by flutter team:
https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm

**Comment by jayeshpansheriya** [comment]
@satvikreddy can you try latest version of awesome_extensions

**Comment by satvikreddy** [comment]
@jayeshpansheriya Thanks for the quick response.
I saw your latest commit and I think this won't work as the package still uses `dart:html` in `src/platform/platform_web.dart`

Attaching snippet from [docs](https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm)
![image](https://github.com/jayeshpansheriya/awesome_extensions/assets/16370824/b039674f-7614-4291-89c1-a5a269344d4f)

**Comment by jayeshpansheriya** [comment]
@satvikreddy its resolved in latest version.

**Comment by satvikreddy** [comment]
@jayeshpansheriya Thanks!! I confirmed that it is working.
