### ISSUE TITLE
Add 'separatedby' method to ListExtension

### ISSUE THREAD

**Issue by ahmadhabibshovo** [jayeshpansheriya/awesome_extensions#40]
is .separedby missing or name changed i could not find .separatedby in 2.0.18

**Comment by jayeshpansheriya** [comment]
Previous which version you used?

**Comment by ahmadhabibshovo** [comment]
sorry , actually it was my mistake ,
i used the awesome_flutter_extension package ,
on that package have a extension .separatedby that is very handy to
separate all widgets of a column or row by only sizebox , awesome extension
should also have that .separatedby

**Comment by jayeshpansheriya** [comment]
@ahmadhabibshovo can you please update title, its not an issue, its new update request, 

Will add this feature in sort time.
