### ISSUE TITLE
Use getters instead of functions where it makes sense

### ISSUE THREAD

**Issue by TekExplorer** [jayeshpansheriya/awesome_extensions#5]
For instance, I am used to using on a String: `myString.isEmpty;` having to replace that with `myString.isBlank();`  is unintuitive and unnecessary

**Comment by jayeshpansheriya** [comment]
@TekExplorer 
Thank you for the feedback.

**Comment by jayeshpansheriya** [comment]
@TekExplorer updated in latest version

**Comment by TekExplorer** [comment]
i'm not sure what you did?
