### ISSUE TITLE
Sized Box from number instead of double

### ISSUE THREAD

**Issue by PAException** [jayeshpansheriya/awesome_extensions#7]
Change target of `Size[d]BoxExtension` from `double` to num to include also integers.
Also need to cast `this` while creating the Widget to `this as double`.

This is currently not possible:  `15.heightBox`

**Comment by jayeshpansheriya** [comment]
@PAException 
Thanks for suggestions.

I will add it, in next release

**Comment by jayeshpansheriya** [comment]
@PAException 
Please check with latest version.

**Comment by jayeshpansheriya** [comment]
> > @PAException 
> > Please check with latest version.
> 
> If it's possible?

Yes, now its works with double as well as num.
Just use latest version.

**Comment by PAException** [comment]
Yes, it is no possible, thanks!

**Comment by jayeshpansheriya** [comment]
@PAException lets me know if any issues, otherwise closing this issue.
